# Generated by Django 5.0.3 on 2024-03-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giangvien',
            fields=[
                ('msgv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password_gv', models.CharField(max_length=20, null=True)),
                ('daymon_gv', models.CharField(max_length=50, null=True)),
                ('hovaten_gv', models.CharField(max_length=30, null=True)),
                ('namsinh_gv', models.DateField()),
                ('gioitinh_gv', models.CharField(max_length=30, null=True)),
                ('diachi_gv', models.CharField(max_length=200, null=True)),
                ('noisinh_gv', models.CharField(max_length=50, null=True)),
                ('quequan_gv', models.CharField(max_length=50, null=True)),
                ('image_gv', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sinhvien',
            fields=[
                ('mssv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password_sv', models.CharField(max_length=20, null=True)),
                ('lop', models.CharField(max_length=20, null=True)),
                ('hovaten_sv', models.CharField(max_length=30, null=True)),
                ('namsinh_sv', models.DateField()),
                ('gioitinh_sv', models.CharField(max_length=30, null=True)),
                ('diachi_sv', models.CharField(max_length=200, null=True)),
                ('noisinh_sv', models.CharField(max_length=50, null=True)),
                ('quequan_sv', models.CharField(max_length=50, null=True)),
                ('image_sv', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
