# Generated by Django 5.0.3 on 2024-03-30 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lophoc_sinhvien_lophoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='lop',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='lophoc',
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='lophoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinh_vien', to='app.lophoc'),
        ),
    ]
