# Generated by Django 5.0.3 on 2024-03-30 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sinhvien_lop_remove_sinhvien_lophoc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monhoc',
            fields=[
                ('ma_mon', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_mon', models.CharField(max_length=255)),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.giangvien')),
            ],
        ),
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_giua_ki', models.FloatField(blank=True, null=True)),
                ('diem_cuoi_ki', models.FloatField(blank=True, null=True)),
                ('diem_tong_ket', models.FloatField(blank=True, null=True)),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.giangvien')),
                ('sinhvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sinhvien')),
                ('monhoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.monhoc')),
            ],
        ),
        migrations.CreateModel(
            name='Thoikhoabieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_hoc', models.IntegerField()),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('ngay_trong_tuan', models.IntegerField()),
                ('monhoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.monhoc')),
                ('sinhvien', models.ManyToManyField(related_name='thoi_khoa_bieu', to='app.sinhvien')),
            ],
        ),
    ]
