# Generated by Django 5.0.3 on 2024-03-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_monhoc_diem_thoikhoabieu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diem',
            new_name='Bangdiem',
        ),
    ]
