# Generated by Django 5.0.3 on 2024-03-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_diem_bangdiem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thoikhoabieu',
            name='sinhvien',
        ),
        migrations.AddField(
            model_name='thoikhoabieu',
            name='lophocmon',
            field=models.ManyToManyField(related_name='thoi_khoa_bieu', to='app.lophoc'),
        ),
    ]
