# Generated by Django 5.0.3 on 2024-03-31 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_thoikhoabieu_sinhvien_thoikhoabieu_lophocmon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='lophocmon',
            field=models.ManyToManyField(related_name='lop_hoc_mon', to='app.lophoc'),
        ),
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoi_khoa_bieu', to='app.monhoc'),
        ),
    ]
