# Generated by Django 5.0.3 on 2024-03-31 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_thoikhoabieu_lophocmon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoikhoabieu', to='app.monhoc'),
        ),
    ]
