# Generated by Django 5.0.3 on 2024-03-31 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_thoikhoabieu_monhoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoikhoabieu',
            name='giang_vien',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.giangvien'),
        ),
        migrations.RemoveField(
            model_name='thoikhoabieu',
            name='lophocmon',
        ),
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='monhoc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.monhoc'),
        ),
        migrations.AddField(
            model_name='thoikhoabieu',
            name='lophocmon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.lophoc'),
        ),
    ]
