# Generated by Django 5.0.3 on 2024-03-31 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_thoikhoabieu_giang_vien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='giang_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giang_vientkb', to='app.giangvien'),
        ),
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='lophocmon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lop_hoctkb', to='app.lophoc'),
        ),
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinh_vientkb', to='app.monhoc'),
        ),
    ]
