# Generated by Django 5.0.3 on 2024-03-31 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_thoikhoabieu_giang_vien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giangvien',
            name='daymon_gv',
        ),
        migrations.RemoveField(
            model_name='monhoc',
            name='giang_vien',
        ),
        migrations.AddField(
            model_name='giangvien',
            name='daymon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giang_vien', to='app.monhoc'),
        ),
        migrations.AddField(
            model_name='monhoc',
            name='mon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_hoc', to='app.monhoc'),
        ),
        migrations.AddField(
            model_name='monhoc',
            name='slug_mon',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='ten_mon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
