# Generated by Django 5.0.3 on 2024-03-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_giangvien_daymon_gv_remove_monhoc_giang_vien_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinhvien',
            old_name='lophoc',
            new_name='hoclop',
        ),
        migrations.RemoveField(
            model_name='giangvien',
            name='daymon',
        ),
        migrations.RemoveField(
            model_name='lophoc',
            name='lop',
        ),
        migrations.RemoveField(
            model_name='monhoc',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='monhoc',
            name='slug_mon',
        ),
        migrations.AddField(
            model_name='monhoc',
            name='giang_vien',
            field=models.ManyToManyField(related_name='monhoc_giangvien', to='app.giangvien'),
        ),
    ]
