# Generated by Django 5.0.3 on 2024-03-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_lophoc_sinhvien_hoclop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monhoc',
            name='giang_vien',
        ),
    ]
