# Generated by Django 5.0.3 on 2024-04-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_diem_cuoi_ki_bangdiem_diem_cuoi_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangdiem',
            name='lop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lophoc'),
        ),
    ]
