# Generated by Django 5.0.3 on 2024-04-03 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_bangdiem_lop'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='monhoc_lophoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.monhoc'),
        ),
        migrations.AlterField(
            model_name='thoikhoabieu',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_hoctkb', to='app.monhoc'),
        ),
    ]
