# Generated by Django 5.0.3 on 2024-04-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_lophoc_monhoc_lophoc_alter_thoikhoabieu_monhoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lophoc',
            name='monhoc_lophoc',
        ),
    ]
