# Generated by Django 5.0.3 on 2024-04-19 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_lophoc_monhoc_lophoc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thoikhoabieu',
            new_name='Lichhoc',
        ),
    ]
